// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Sat Oct 13 15:26:53 2018

control_ndiag_in control_ndiag_in_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.areset(areset_sig) ,	// input  areset_sig
	.diag_done(diag_done_sig) ,	// input  diag_done_sig
	.bu1(bu1_sig) ,	// input [31:0] bu1_sig
	.bu2(bu2_sig) ,	// input [31:0] bu2_sig
	.bu3(bu3_sig) ,	// input [31:0] bu3_sig
	.bu4(bu4_sig) ,	// input [31:0] bu4_sig
	.ndiag_out(ndiag_out_sig) 	// output [31:0] ndiag_out_sig
);

defparam control_ndiag_in_inst.sBU1 = 'b00;
defparam control_ndiag_in_inst.sBU2 = 'b01;
defparam control_ndiag_in_inst.sBU3 = 'b10;
defparam control_ndiag_in_inst.sBU4 = 'b11;
